routes:
  - origin: DEL
    destination: BOM
    route_code: DEL-BOM
    o_lat: 28.5562
    o_lon: 77.1000
    d_lat: 19.0896
    d_lon: 72.8656
    lead_times: [1, 7, 15, 30, 45]

  - origin: DEL
    destination: BLR
    route_code: DEL-BLR
    o_lat: 28.5562
    o_lon: 77.1000
    d_lat: 13.1986
    d_lon: 77.7066
    lead_times: [1, 7, 15, 30, 45]

  - origin: BOM
    destination: BLR
    route_code: BOM-BLR
    o_lat: 19.0896
    o_lon: 72.8656
    d_lat: 13.1986
    d_lon: 77.7066
    lead_times: [1, 7, 15, 30, 45]

  - origin: DEL
    destination: CCU
    route_code: DEL-CCU
    o_lat: 28.5562
    o_lon: 77.1000
    d_lat: 22.6520
    d_lon: 88.4463
    lead_times: [1, 7, 15, 30, 45]

  - origin: BLR
    destination: HYD
    route_code: BLR-HYD
    o_lat: 13.1986
    o_lon: 77.7066
    d_lat: 17.2403
    d_lon: 78.4294
    lead_times: [1, 7, 15, 30, 45]

  - origin: MAA
    destination: DEL
    route_code: MAA-DEL
    o_lat: 12.9941
    o_lon: 80.1709
    d_lat: 28.5562
    d_lon: 77.1000
    lead_times: [1, 7, 15, 30, 45]
